### ISSUE TITLE
UnicodeDecodeError when initializing HanziDecomposer

### ISSUE THREAD

**Issue by chaudhga** [Synkied/hanzipy#5]
When I try to initialize `HanziDecomposer`, I get a `UnicodeDecodeError`. The error seems to stem from the `init_decomposition()` method when it tries to load a JSON file. Here's the traceback:

Traceback (most recent call last):
  File "C:\MyPC\MyProject\HanziPyTest.py.py", line 12, in <module>
    decomposer = HanziDecomposer()
  File "C:\MyPC\MyProject\venv\lib\site-packages\hanzipy\decomposer.py", line 23, in __init__
    self.init_decomposition()
  File "C:\MyPC\MyProject\venv\lib\site-packages\hanzipy\decomposer.py", line 52, in init_decomposition
    self.radicals = json.load(radicals_file)
  File "C:\MyPC\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\MyPC\AppData\Local\Programs\Python\Python39\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 728: character maps to <undefined>

**Environment:** 
- OS: Windows11
- Python version: Python 3.9
- hanzipy version: 1.0.3

**Steps to Reproduce:**
Here's a minimal code snippet that reproduces the error:

```python
from hanzipy import HanziDecomposer
decomposer = HanziDecomposer()

**Comment by Synkied** [comment]
Hey, thank you very much for you pull request, I really appreciate it!

I indeed did not test my code on Windows and I'm sorry about that.

I tested your fix and it seems to work, thanks again!

I'm only replacing simple quotes by double quotes for consistency.

**Comment by Synkied** [comment]
https://github.com/Synkied/hanzipy/releases/tag/v1.0.4 release thanks to your contribution.

Really appreciate it, once again!
